//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocketEcommerceAPI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocketEcommerceAPI.App_LocalResources.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action providers can be executed from here.  An action provider is designed to do a single action on the store, usually to update records or fix problems.
        ///&lt;br/&gt;
        ///The assembly that will be executed should be installed into the bin folder and then the correct assembly, namespace, class and extra data can be added into the fields below. &lt;br/&gt;The action provider assembly should inherit the &quot;ActionProvider&quot; class..
        /// </summary>
        internal static string actionprovider_Help {
            get {
                return ResourceManager.GetString("actionprovider.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Provider.
        /// </summary>
        internal static string actionprovider_Text {
            get {
                return ResourceManager.GetString("actionprovider.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string assembly_Text {
            get {
                return ResourceManager.GetString("assembly.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string completed_Text {
            get {
                return ResourceManager.GetString("completed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has failed to be sent to {email}.  Please try again.  If the problem continues ask your webmaster to check your SMTP and portal config..
        /// </summary>
        internal static string emailfail_Msg {
            get {
                return ResourceManager.GetString("emailfail.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Failure..
        /// </summary>
        internal static string emailfail_Text {
            get {
                return ResourceManager.GetString("emailfail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been sent to {email}.
        /// </summary>
        internal static string emailsent_Msg {
            get {
                return ResourceManager.GetString("emailsent.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent..
        /// </summary>
        internal static string emailsent_Text {
            get {
                return ResourceManager.GetString("emailsent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error_Text {
            get {
                return ResourceManager.GetString("error.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string example_Text {
            get {
                return ResourceManager.GetString("example.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting this shop will set it as the default for all new portal shops created on this install.  A &quot;default_portalshop.xml&quot; file is created in the RocketEcommerceAPI folder.  When a new portal shop is created this xml data will be used to create the new portal..
        /// </summary>
        internal static string exportconfig_Help {
            get {
                return ResourceManager.GetString("exportconfig.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To import the data from OpenStore v3 or v4, rename the exported XML file to &quot;\Portals\{portalid}\DNNrocketTemp\openstore3_export.xml&quot; and place in the root of the portal. Images go in &quot;\Portals\{portalid}\DNNrocket\RocketEcommerceAPI\images&quot; to have them imported..
        /// </summary>
        internal static string importopenstore3config_Help {
            get {
                return ResourceManager.GetString("importopenstore3config.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import OpenStore.
        /// </summary>
        internal static string importopenstore3config_Text {
            get {
                return ResourceManager.GetString("importopenstore3config.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have opted to NOT pay online.  
        ///
        ///Please make your bank payment as soon as possible to the account below. Insert the order number in the reference field and include your name as well if it is different from the acccount name..
        /// </summary>
        internal static string message_bankinstructions_Default {
            get {
                return ResourceManager.GetString("message_bankinstructions.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message displayed on the order email, when the order has not been paid via the on-line interface..
        /// </summary>
        internal static string message_bankinstructions_Help {
            get {
                return ResourceManager.GetString("message_bankinstructions.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking Instructions.
        /// </summary>
        internal static string message_bankinstructions_Text {
            get {
                return ResourceManager.GetString("message_bankinstructions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment can be made on-line through our secure link to the bank.  Your order will be processed immediately..
        /// </summary>
        internal static string message_bankpayment_Default {
            get {
                return ResourceManager.GetString("message_bankpayment.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message appears on the front office next to the online bank payment option..
        /// </summary>
        internal static string message_bankpayment_Help {
            get {
                return ResourceManager.GetString("message_bankpayment.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Bank Payment Button Message.
        /// </summary>
        internal static string message_bankpayment_Text {
            get {
                return ResourceManager.GetString("message_bankpayment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order was cancelled or the payment failed. Contact your bank if you need assistance with your credit card, or contact us if you believe there is a problem with the checkout..
        /// </summary>
        internal static string message_checkoutfail_Default {
            get {
                return ResourceManager.GetString("message_checkoutfail.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text is displayed on the website, to the client, after a failed order..
        /// </summary>
        internal static string message_checkoutfail_Help {
            get {
                return ResourceManager.GetString("message_checkoutfail.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Fail message.
        /// </summary>
        internal static string message_checkoutfail_Text {
            get {
                return ResourceManager.GetString("message_checkoutfail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order. You will receive an emailed confirmation containing all order details. Please check your junk email folders if you don&apos;t receive it within 30 minutes. Take note of the number below if you wish to contact us about this order..
        /// </summary>
        internal static string message_checkoutok_Default {
            get {
                return ResourceManager.GetString("message_checkoutok.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text is displayed on the website, to the client, after a successful order..
        /// </summary>
        internal static string message_checkoutok_Help {
            get {
                return ResourceManager.GetString("message_checkoutok.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout OK message.
        /// </summary>
        internal static string message_checkoutok_Text {
            get {
                return ResourceManager.GetString("message_checkoutok.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order. We&apos;re here to help! Call us during office hours Monday to Friday, or visit us in-store if you have any questions about your order..
        /// </summary>
        internal static string message_emailorder_Default {
            get {
                return ResourceManager.GetString("message_emailorder.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text that is displayed on the successful order email, which is sent to the client..
        /// </summary>
        internal static string message_emailorder_Help {
            get {
                return ResourceManager.GetString("message_emailorder.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Order Message.
        /// </summary>
        internal static string message_emailorder_Text {
            get {
                return ResourceManager.GetString("message_emailorder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Order Subject.
        /// </summary>
        internal static string message_emailordersubject_Text {
            get {
                return ResourceManager.GetString("message_emailordersubject.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Payment Subject.
        /// </summary>
        internal static string message_emailpaymentsubject_Text {
            get {
                return ResourceManager.GetString("message_emailpaymentsubject.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment can be made by Cheque or Bank Transfer.  Your order may be delayed until payment is received..
        /// </summary>
        internal static string message_manualpay_Default {
            get {
                return ResourceManager.GetString("message_manualpay.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message appears on the front office next to the manual payment option..
        /// </summary>
        internal static string message_manualpay_Help {
            get {
                return ResourceManager.GetString("message_manualpay.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Payment Button Message.
        /// </summary>
        internal static string message_manualpay_Text {
            get {
                return ResourceManager.GetString("message_manualpay.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form allows you to pay us.  Please enter your details and click &quot;Pay&quot;.  
        ///You will be redirected to the bank for secure payment..
        /// </summary>
        internal static string message_paymentform_Default {
            get {
                return ResourceManager.GetString("message_paymentform.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is displayed on the single payment form..
        /// </summary>
        internal static string message_paymentform_Help {
            get {
                return ResourceManager.GetString("message_paymentform.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Form Message.
        /// </summary>
        internal static string message_paymentform_Text {
            get {
                return ResourceManager.GetString("message_paymentform.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy payment can be made on our secure payment website.
        ///  
        ///Click the &quot;Pay&quot; button below to open our payment form..
        /// </summary>
        internal static string message_paymentformemail_Default {
            get {
                return ResourceManager.GetString("message_paymentformemail.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an email is sent for a payment, the email will contain this message. .
        /// </summary>
        internal static string message_paymentformemail_Help {
            get {
                return ResourceManager.GetString("message_paymentformemail.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Form Email Message.
        /// </summary>
        internal static string message_paymentformemail_Text {
            get {
                return ResourceManager.GetString("message_paymentformemail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment has been refused or cancelled, please try again..
        /// </summary>
        internal static string message_paymentformfail_Default {
            get {
                return ResourceManager.GetString("message_paymentformfail.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message that is displayed to the client when they return from the bank with a FAILED payment status..
        /// </summary>
        internal static string message_paymentformfail_Help {
            get {
                return ResourceManager.GetString("message_paymentformfail.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Form Fail Message.
        /// </summary>
        internal static string message_paymentformfail_Text {
            get {
                return ResourceManager.GetString("message_paymentformfail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Payment has been successfully completed..
        /// </summary>
        internal static string message_paymentformok_Default {
            get {
                return ResourceManager.GetString("message_paymentformok.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message that is displayed to the client when they return from the bank with a SUCCESSFUL payment status..
        /// </summary>
        internal static string message_paymentformok_Help {
            get {
                return ResourceManager.GetString("message_paymentformok.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Form OK message.
        /// </summary>
        internal static string message_paymentformok_Text {
            get {
                return ResourceManager.GetString("message_paymentformok.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your payment..
        /// </summary>
        internal static string message_paymentreceived_Default {
            get {
                return ResourceManager.GetString("message_paymentreceived.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text that will displayed on the &quot;Payment OK&quot; email sent to the client.
        /// </summary>
        internal static string message_paymentreceived_Help {
            get {
                return ResourceManager.GetString("message_paymentreceived.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Received.
        /// </summary>
        internal static string message_paymentreceived_Text {
            get {
                return ResourceManager.GetString("message_paymentreceived.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are welcome to pick your order up from us in store during opening hours. Please ring us if you want to ensure it is ready for pickup..
        /// </summary>
        internal static string message_storepickup_Default {
            get {
                return ResourceManager.GetString("message_storepickup.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a pickup option for shipping, this message is displayed on the website during shipping selection..
        /// </summary>
        internal static string message_storepickup_Help {
            get {
                return ResourceManager.GetString("message_storepickup.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Pickup.
        /// </summary>
        internal static string message_storepickup_Text {
            get {
                return ResourceManager.GetString("message_storepickup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have opted to NOT pay online.  
        ///
        ///An email with instructions has been send to your email address..
        /// </summary>
        internal static string message_waitingforpayment_Default {
            get {
                return ResourceManager.GetString("message_waitingforpayment.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &quot;manual payment&quot; is used, the payment is NOT paid online and must be sent to the merchant via other methods (cheque, money, transfer, etc.).  This message is displayed on the bank return after clicking pay on the &quot;manual payment&quot; option..
        /// </summary>
        internal static string message_waitingforpayment_Help {
            get {
                return ResourceManager.GetString("message_waitingforpayment.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For Payment.
        /// </summary>
        internal static string message_waitingforpayment_Text {
            get {
                return ResourceManager.GetString("message_waitingforpayment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.Class.
        /// </summary>
        internal static string namespaceclass_Text {
            get {
                return ResourceManager.GetString("namespaceclass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sub-categories in this category..
        /// </summary>
        internal static string nosubcategories_Text {
            get {
                return ResourceManager.GetString("nosubcategories.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will reset ALL notification messages back to the default.  Current notifications, for the ALL languages, will be lost.  You must also save the messages after a reset.
        ///Are you Sure ?.
        /// </summary>
        internal static string notificationreset_Msg {
            get {
                return ResourceManager.GetString("notificationreset.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Reset.
        /// </summary>
        internal static string notificationreset_Text {
            get {
                return ResourceManager.GetString("notificationreset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Payment Page URL is the full URL where payment can be made.  This creates a button in the payment admin and can also be used to create a link..
        /// </summary>
        internal static string pageslinks_paymentpageurl_Help {
            get {
                return ResourceManager.GetString("pageslinks_paymentpageurl.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Page URL.
        /// </summary>
        internal static string pageslinks_paymentpageurl_Text {
            get {
                return ResourceManager.GetString("pageslinks_paymentpageurl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product detail URL is used to create SEO urls on the website.  It uses product tokens to build a relative URL for the product detail page..
        /// </summary>
        internal static string pageslinks_productdetail_Help {
            get {
                return ResourceManager.GetString("pageslinks_productdetail.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product detail URL.
        /// </summary>
        internal static string pageslinks_productdetail_Text {
            get {
                return ResourceManager.GetString("pageslinks_productdetail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list URL is used to create SEO urls on the website.  It uses product and category tokens to build a relative URL for the product list page..
        /// </summary>
        internal static string pageslinks_productlist_Help {
            get {
                return ResourceManager.GetString("pageslinks_productlist.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list URL.
        /// </summary>
        internal static string pageslinks_productlist_Text {
            get {
                return ResourceManager.GetString("pageslinks_productlist.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseting the shop will restore all shop settings back to the default for the system.  (Usually created by the Export PortalShop).
        /// </summary>
        internal static string resetportalshop_Help {
            get {
                return ResourceManager.GetString("resetportalshop.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Shop.
        /// </summary>
        internal static string resetportalshop_Text {
            get {
                return ResourceManager.GetString("resetportalshop.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of hours that need to have passed from the last scheduler run before the scheduler will run again.  This is also controlled in DNN, but is usually setup for every hour.  Usually we need to clear the database and do other operations only once a day.  Operations that need to run every hour are not effected by this setting..
        /// </summary>
        internal static string schedulerrunhours_Help {
            get {
                return ResourceManager.GetString("schedulerrunhours.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Run Hours.
        /// </summary>
        internal static string schedulerrunhours_Text {
            get {
                return ResourceManager.GetString("schedulerrunhours.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLs for pages on the client webiste can be added here, this allows for SEO links between API calls that happen.&lt;br/&gt;
        ///URLs can have tokens added for parameters that need to be added to the page link.  &lt;br/&gt;
        ///(User standard url format for compatibility across systems)
        ///
        ///.
        /// </summary>
        internal static string urlredirects_Text {
            get {
                return ResourceManager.GetString("urlredirects.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do a portal level validation of the website.  This willl run a number of test and fix any errors.  Usually this needs to be run when a website has been migrated to another server.  Zero will activate the sceduler on the DNN control parameters..
        /// </summary>
        internal static string validateshop_Help {
            get {
                return ResourceManager.GetString("validateshop.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Shop.
        /// </summary>
        internal static string validateshop_Text {
            get {
                return ResourceManager.GetString("validateshop.Text", resourceCulture);
            }
        }
    }
}
