//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocketEcommerceAPI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocketEcommerceAPI.App_LocalResources.RE", typeof(RE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string accountname_Text {
            get {
                return ResourceManager.GetString("accountname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string accountnumber_Text {
            get {
                return ResourceManager.GetString("accountnumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different configurations or options will make some menu options obsolete.  This allow you to select which options should appear on the clients admin menu..
        /// </summary>
        internal static string activeadminmenu_Help {
            get {
                return ResourceManager.GetString("activeadminmenu.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Admin Menu.
        /// </summary>
        internal static string activeadminmenu_Text {
            get {
                return ResourceManager.GetString("activeadminmenu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Shop.
        /// </summary>
        internal static string activeportal_Text {
            get {
                return ResourceManager.GetString("activeportal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address_Text {
            get {
                return ResourceManager.GetString("address.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        internal static string address1_Text {
            get {
                return ResourceManager.GetString("address1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        internal static string address2_Text {
            get {
                return ResourceManager.GetString("address2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Basket.
        /// </summary>
        internal static string addtobasket_Text {
            get {
                return ResourceManager.GetString("addtobasket.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string administrator_Text {
            get {
                return ResourceManager.GetString("administrator.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string afternoon_Text {
            get {
                return ResourceManager.GetString("afternoon.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all_Text {
            get {
                return ResourceManager.GetString("all.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        internal static string allproducts_Text {
            get {
                return ResourceManager.GetString("allproducts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount_Text {
            get {
                return ResourceManager.GetString("amount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        internal static string amountdue_Text {
            get {
                return ResourceManager.GetString("amountdue.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        internal static string amountpaid_Text {
            get {
                return ResourceManager.GetString("amountpaid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppTheme Project.
        /// </summary>
        internal static string appthemeprojectname_Text {
            get {
                return ResourceManager.GetString("appthemeprojectname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string attention_Text {
            get {
                return ResourceManager.GetString("attention.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details.
        /// </summary>
        internal static string bankdetails_Text {
            get {
                return ResourceManager.GetString("bankdetails.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string bankname_Text {
            get {
                return ResourceManager.GetString("bankname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure on-line Payment.
        /// </summary>
        internal static string bankpayment_Text {
            get {
                return ResourceManager.GetString("bankpayment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        internal static string billingaddress_Text {
            get {
                return ResourceManager.GetString("billingaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string brand_Text {
            get {
                return ResourceManager.GetString("brand.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string buy_Text {
            get {
                return ResourceManager.GetString("buy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Statistics.
        /// </summary>
        internal static string calcstats_Text {
            get {
                return ResourceManager.GetString("calcstats.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string cart_Text {
            get {
                return ResourceManager.GetString("cart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Admin.
        /// </summary>
        internal static string cartadmin_Text {
            get {
                return ResourceManager.GetString("cartadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of days to retain carts in the Database.  After the number of days has elapsed, the cart will be removed from the database..
        /// </summary>
        internal static string cartdays_Help {
            get {
                return ResourceManager.GetString("cartdays.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain Cart (Days).
        /// </summary>
        internal static string cartdays_Text {
            get {
                return ResourceManager.GetString("cartdays.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of carts that can be kepted in the database. Once the portal carts have passed this number in the database the system will automatically removed the extra carts over this limit if they are over 1 hour old, regardless of the &quot;Retain Cart&quot; setting..
        /// </summary>
        internal static string cartlimit_Help {
            get {
                return ResourceManager.GetString("cartlimit.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Record Limit.
        /// </summary>
        internal static string cartlimit_Text {
            get {
                return ResourceManager.GetString("cartlimit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to All Parent Categories.
        /// </summary>
        internal static string cascade_Text {
            get {
                return ResourceManager.GetString("cascade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string catalog_Text {
            get {
                return ResourceManager.GetString("catalog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string categories_Text {
            get {
                return ResourceManager.GetString("categories.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category_Text {
            get {
                return ResourceManager.GetString("category.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string categoryadmin_Text {
            get {
                return ResourceManager.GetString("categoryadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Type.
        /// </summary>
        internal static string checkouttype_Text {
            get {
                return ResourceManager.GetString("checkouttype.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery + Collection,Delivery,Collection,Custom.
        /// </summary>
        internal static string checkouttypetext_Text {
            get {
                return ResourceManager.GetString("checkouttypetext.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your collection Time and Day.
        /// </summary>
        internal static string chosecollection_Text {
            get {
                return ResourceManager.GetString("chosecollection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city_Text {
            get {
                return ResourceManager.GetString("city.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string client_Text {
            get {
                return ResourceManager.GetString("client.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Notes.
        /// </summary>
        internal static string clientnotes_Text {
            get {
                return ResourceManager.GetString("clientnotes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string clients_Text {
            get {
                return ResourceManager.GetString("clients.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close_Text {
            get {
                return ResourceManager.GetString("close.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string closed_Text {
            get {
                return ResourceManager.GetString("closed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string collectinstore_Text {
            get {
                return ResourceManager.GetString("collectinstore.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On Collection DatePicker..
        /// </summary>
        internal static string collectionon_Text {
            get {
                return ResourceManager.GetString("collectionon.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minutes between each collection select option.
        /// </summary>
        internal static string collectionsegments_Text {
            get {
                return ResourceManager.GetString("collectionsegments.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Time.
        /// </summary>
        internal static string collectiontime_Text {
            get {
                return ResourceManager.GetString("collectiontime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string company_Text {
            get {
                return ResourceManager.GetString("company.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string companyname_Text {
            get {
                return ResourceManager.GetString("companyname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Code.
        /// </summary>
        internal static string connectioncode_Text {
            get {
                return ResourceManager.GetString("connectioncode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        internal static string contactdetails_Text {
            get {
                return ResourceManager.GetString("contactdetails.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        internal static string contactemail_Text {
            get {
                return ResourceManager.GetString("contactemail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string contacts_Text {
            get {
                return ResourceManager.GetString("contacts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string contactus_Text {
            get {
                return ResourceManager.GetString("contactus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Shopping.
        /// </summary>
        internal static string continueshopping_Text {
            get {
                return ResourceManager.GetString("continueshopping.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Type.
        /// </summary>
        internal static string controltype_Text {
            get {
                return ResourceManager.GetString("controltype.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copy_Text {
            get {
                return ResourceManager.GetString("copy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country_Text {
            get {
                return ResourceManager.GetString("country.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        internal static string currencycode_Text {
            get {
                return ResourceManager.GetString("currencycode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Culture Code.
        /// </summary>
        internal static string currencyculturecode_Text {
            get {
                return ResourceManager.GetString("currencyculturecode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard_Text {
            get {
                return ResourceManager.GetString("dashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string database_Text {
            get {
                return ResourceManager.GetString("database.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date_Text {
            get {
                return ResourceManager.GetString("date.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string day_Text {
            get {
                return ResourceManager.GetString("day.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Category.
        /// </summary>
        internal static string defaultcategory_Text {
            get {
                return ResourceManager.GetString("defaultcategory.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string delivery_Text {
            get {
                return ResourceManager.GetString("delivery.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered to your address..
        /// </summary>
        internal static string deliverymsg_Text {
            get {
                return ResourceManager.GetString("deliverymsg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Page URL.
        /// </summary>
        internal static string detailpageurl_Text {
            get {
                return ResourceManager.GetString("detailpageurl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details_Text {
            get {
                return ResourceManager.GetString("details.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string discount_Text {
            get {
                return ResourceManager.GetString("discount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code.
        /// </summary>
        internal static string discountcode_Text {
            get {
                return ResourceManager.GetString("discountcode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Methods.
        /// </summary>
        internal static string discountmethods_Text {
            get {
                return ResourceManager.GetString("discountmethods.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Price.
        /// </summary>
        internal static string discountprice_Text {
            get {
                return ResourceManager.GetString("discountprice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Address.
        /// </summary>
        internal static string displayaddress_Text {
            get {
                return ResourceManager.GetString("displayaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string document_Text {
            get {
                return ResourceManager.GetString("document.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        internal static string due_Text {
            get {
                return ResourceManager.GetString("due.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email_Text {
            get {
                return ResourceManager.GetString("email.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to send e-mail.
        /// </summary>
        internal static string emailfail_Text {
            get {
                return ResourceManager.GetString("emailfail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note to recipient.
        /// </summary>
        internal static string emailmessage_Text {
            get {
                return ResourceManager.GetString("emailmessage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        internal static string emailsent_Text {
            get {
                return ResourceManager.GetString("emailsent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string employees_Text {
            get {
                return ResourceManager.GetString("employees.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Basket is Empty.
        /// </summary>
        internal static string emptybasket_Text {
            get {
                return ResourceManager.GetString("emptybasket.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Domain URL.
        /// </summary>
        internal static string enginedomain_Text {
            get {
                return ResourceManager.GetString("enginedomain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Engine URL is the portal url that is used as the e-commerce engine and has the user authentication linked to it.  It is autogenerated using a GUID key (as the sub-domain) and a root domain.  Usually the root domain will be the default site, but it can be altered to use another url.  The EngineUrl DNS will need to be pointing at the server and attached to the website binding.  It is automatically created as a portal alias.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;  WARNING: Incorrectly altering this URL can stop the e-commerce engin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string engineurl_Help {
            get {
                return ResourceManager.GetString("engineurl.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine URL.
        /// </summary>
        internal static string engineurl_Text {
            get {
                return ResourceManager.GetString("engineurl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event List.
        /// </summary>
        internal static string eventlist_Text {
            get {
                return ResourceManager.GetString("eventlist.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        internal static string eventname_Text {
            get {
                return ResourceManager.GetString("eventname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string export_Text {
            get {
                return ResourceManager.GetString("export.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string extra_Text {
            get {
                return ResourceManager.GetString("extra.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string fail_Text {
            get {
                return ResourceManager.GetString("fail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string firstname_Text {
            get {
                return ResourceManager.GetString("firstname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string from_Text {
            get {
                return ResourceManager.GetString("from.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Email.
        /// </summary>
        internal static string fromemail_Text {
            get {
                return ResourceManager.GetString("fromemail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string general_Text {
            get {
                return ResourceManager.GetString("general.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string generalsettings_Text {
            get {
                return ResourceManager.GetString("generalsettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grams.
        /// </summary>
        internal static string grams_Text {
            get {
                return ResourceManager.GetString("grams.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string hidden_Text {
            get {
                return ResourceManager.GetString("hidden.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string history_Text {
            get {
                return ResourceManager.GetString("history.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string htmltext_Text {
            get {
                return ResourceManager.GetString("htmltext.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your images here, by dragging and dropping or paste from the clipboard on the area below.  Or by using the upload button to select images from your file system..
        /// </summary>
        internal static string imageupload_Msg {
            get {
                return ResourceManager.GetString("imageupload.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Upload.
        /// </summary>
        internal static string imageupload_Text {
            get {
                return ResourceManager.GetString("imageupload.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When filtering search only the selected category.  If unchecked filters will work on all products..
        /// </summary>
        internal static string incategoryfilter_Help {
            get {
                return ResourceManager.GetString("incategoryfilter.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Category Filter.
        /// </summary>
        internal static string incategoryfilter_Text {
            get {
                return ResourceManager.GetString("incategoryfilter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Notes.
        /// </summary>
        internal static string internalnotes_Text {
            get {
                return ResourceManager.GetString("internalnotes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup has not been completed..
        /// </summary>
        internal static string invalidsetup_Text {
            get {
                return ResourceManager.GetString("invalidsetup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Ref.
        /// </summary>
        internal static string invoiceref_Text {
            get {
                return ResourceManager.GetString("invoiceref.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item(s).
        /// </summary>
        internal static string items_Text {
            get {
                return ResourceManager.GetString("items.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string justify_Text {
            get {
                return ResourceManager.GetString("justify.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string keywords_Text {
            get {
                return ResourceManager.GetString("keywords.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lastname_Text {
            get {
                return ResourceManager.GetString("lastname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Page URL.
        /// </summary>
        internal static string listpageurl_Text {
            get {
                return ResourceManager.GetString("listpageurl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Active.
        /// </summary>
        internal static string makeactive_Text {
            get {
                return ResourceManager.GetString("makeactive.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Panel.
        /// </summary>
        internal static string managementpanel_Text {
            get {
                return ResourceManager.GetString("managementpanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string manager_Text {
            get {
                return ResourceManager.GetString("manager.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Email.
        /// </summary>
        internal static string manageremail_Text {
            get {
                return ResourceManager.GetString("manageremail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Password.
        /// </summary>
        internal static string managerpassword_Text {
            get {
                return ResourceManager.GetString("managerpassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows the product list to be sorted in a manual sort order.  Each category can have a sort order for products.  .
        /// </summary>
        internal static string manualcategoryorderby_Help {
            get {
                return ResourceManager.GetString("manualcategoryorderby.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Category Order By.
        /// </summary>
        internal static string manualcategoryorderby_Text {
            get {
                return ResourceManager.GetString("manualcategoryorderby.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a default manual sort order for products.  This uses the &quot;Sort Order&quot; field in the product..
        /// </summary>
        internal static string manualorderby_Help {
            get {
                return ResourceManager.GetString("manualorderby.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Default Sort Order.
        /// </summary>
        internal static string manualorderby_Text {
            get {
                return ResourceManager.GetString("manualorderby.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by Cheque or Bank Transfer.
        /// </summary>
        internal static string manualpay_Text {
            get {
                return ResourceManager.GetString("manualpay.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxium Amount of Products.
        /// </summary>
        internal static string maxproducts_Text {
            get {
                return ResourceManager.GetString("maxproducts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string memebers_Text {
            get {
                return ResourceManager.GetString("memebers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Contacts.
        /// </summary>
        internal static string merchantcontacts_Text {
            get {
                return ResourceManager.GetString("merchantcontacts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string models_Text {
            get {
                return ResourceManager.GetString("models.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string modify_Text {
            get {
                return ResourceManager.GetString("modify.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        internal static string morning_Text {
            get {
                return ResourceManager.GetString("morning.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name_Text {
            get {
                return ResourceManager.GetString("name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Payment.
        /// </summary>
        internal static string newpayment_Text {
            get {
                return ResourceManager.GetString("newpayment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Portal.
        /// </summary>
        internal static string newportal_Text {
            get {
                return ResourceManager.GetString("newportal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notes_Text {
            get {
                return ResourceManager.GetString("notes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string notification_Text {
            get {
                return ResourceManager.GetString("notification.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string notifications_Text {
            get {
                return ResourceManager.GetString("notifications.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string number_Text {
            get {
                return ResourceManager.GetString("number.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok_Text {
            get {
                return ResourceManager.GetString("ok.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open_Text {
            get {
                return ResourceManager.GetString("open.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Times.
        /// </summary>
        internal static string opentimes_Text {
            get {
                return ResourceManager.GetString("opentimes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string optional_Text {
            get {
                return ResourceManager.GetString("optional.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options_Text {
            get {
                return ResourceManager.GetString("options.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string order_Text {
            get {
                return ResourceManager.GetString("order.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order management.
        /// </summary>
        internal static string orderadmin_Text {
            get {
                return ResourceManager.GetString("orderadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string orderdate_Text {
            get {
                return ResourceManager.GetString("orderdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination of Order email.
        /// </summary>
        internal static string orderemail_Text {
            get {
                return ResourceManager.GetString("orderemail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        internal static string ordernumber_Text {
            get {
                return ResourceManager.GetString("ordernumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string orders_Text {
            get {
                return ResourceManager.GetString("orders.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        internal static string orderstatus_Text {
            get {
                return ResourceManager.GetString("orderstatus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string orderstatus0_Text {
            get {
                return ResourceManager.GetString("orderstatus0.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string orderstatus10_Text {
            get {
                return ResourceManager.GetString("orderstatus10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string orderstatus100_Text {
            get {
                return ResourceManager.GetString("orderstatus100.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string orderstatus110_Text {
            get {
                return ResourceManager.GetString("orderstatus110.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string orderstatus120_Text {
            get {
                return ResourceManager.GetString("orderstatus120.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string orderstatus130_Text {
            get {
                return ResourceManager.GetString("orderstatus130.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special / Edit.
        /// </summary>
        internal static string orderstatus140_Text {
            get {
                return ResourceManager.GetString("orderstatus140.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Failed.
        /// </summary>
        internal static string orderstatus150_Text {
            get {
                return ResourceManager.GetString("orderstatus150.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Payment.
        /// </summary>
        internal static string orderstatus160_Text {
            get {
                return ResourceManager.GetString("orderstatus160.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Not Verified.
        /// </summary>
        internal static string orderstatus170_Text {
            get {
                return ResourceManager.GetString("orderstatus170.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overpaid.
        /// </summary>
        internal static string orderstatus180_Text {
            get {
                return ResourceManager.GetString("orderstatus180.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overpaid Not Verified.
        /// </summary>
        internal static string orderstatus190_Text {
            get {
                return ResourceManager.GetString("orderstatus190.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string orderstatus20_Text {
            get {
                return ResourceManager.GetString("orderstatus20.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string orderstatus200_Text {
            get {
                return ResourceManager.GetString("orderstatus200.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Not Verified.
        /// </summary>
        internal static string orderstatus210_Text {
            get {
                return ResourceManager.GetString("orderstatus210.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Payment.
        /// </summary>
        internal static string orderstatus220_Text {
            get {
                return ResourceManager.GetString("orderstatus220.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Bank.
        /// </summary>
        internal static string orderstatus30_Text {
            get {
                return ResourceManager.GetString("orderstatus30.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string orderstatus40_Text {
            get {
                return ResourceManager.GetString("orderstatus40.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Accepted.
        /// </summary>
        internal static string orderstatus50_Text {
            get {
                return ResourceManager.GetString("orderstatus50.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Not Verified.
        /// </summary>
        internal static string orderstatus60_Text {
            get {
                return ResourceManager.GetString("orderstatus60.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Payment.
        /// </summary>
        internal static string orderstatus70_Text {
            get {
                return ResourceManager.GetString("orderstatus70.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Stock.
        /// </summary>
        internal static string orderstatus80_Text {
            get {
                return ResourceManager.GetString("orderstatus80.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being Manufactured.
        /// </summary>
        internal static string orderstatus90_Text {
            get {
                return ResourceManager.GetString("orderstatus90.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Status.
        /// </summary>
        internal static string orderstatusall_Text {
            get {
                return ResourceManager.GetString("orderstatusall.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string paid_Text {
            get {
                return ResourceManager.GetString("paid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        internal static string parentcategory_Text {
            get {
                return ResourceManager.GetString("parentcategory.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string pay_Text {
            get {
                return ResourceManager.GetString("pay.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string payment_Text {
            get {
                return ResourceManager.GetString("payment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment management.
        /// </summary>
        internal static string paymentadmin_Text {
            get {
                return ResourceManager.GetString("paymentadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        internal static string paymentmethods_Text {
            get {
                return ResourceManager.GetString("paymentmethods.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Provider.
        /// </summary>
        internal static string paymentprovider_Text {
            get {
                return ResourceManager.GetString("paymentprovider.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Providers.
        /// </summary>
        internal static string paymentproviders_Text {
            get {
                return ResourceManager.GetString("paymentproviders.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Payment has been requested.
        /// </summary>
        internal static string paymentrequest_Text {
            get {
                return ResourceManager.GetString("paymentrequest.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string payments_Text {
            get {
                return ResourceManager.GetString("payments.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Status.
        /// </summary>
        internal static string paymentstatus_Text {
            get {
                return ResourceManager.GetString("paymentstatus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone_Text {
            get {
                return ResourceManager.GetString("phone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        internal static string pleaseselect_Text {
            get {
                return ResourceManager.GetString("pleaseselect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Settings.
        /// </summary>
        internal static string portalsettings_Text {
            get {
                return ResourceManager.GetString("portalsettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops.
        /// </summary>
        internal static string portalshops_Text {
            get {
                return ResourceManager.GetString("portalshops.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post box.
        /// </summary>
        internal static string postbox_Text {
            get {
                return ResourceManager.GetString("postbox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string postcode_Text {
            get {
                return ResourceManager.GetString("postcode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefered Culture.
        /// </summary>
        internal static string preferedculturecode_Text {
            get {
                return ResourceManager.GetString("preferedculturecode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price_Text {
            get {
                return ResourceManager.GetString("price.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Label.
        /// </summary>
        internal static string printlabel_Text {
            get {
                return ResourceManager.GetString("printlabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string product_Text {
            get {
                return ResourceManager.GetString("product.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string productadmin_Text {
            get {
                return ResourceManager.GetString("productadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecking the data section will make the product data section hidden in the product admin..
        /// </summary>
        internal static string productdata_Help {
            get {
                return ResourceManager.GetString("productdata.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Data Sections.
        /// </summary>
        internal static string productdata_Text {
            get {
                return ResourceManager.GetString("productdata.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models&amp;nbsp;&amp;nbsp;&amp;nbsp;,Images&amp;nbsp;&amp;nbsp;&amp;nbsp;,Options&amp;nbsp;&amp;nbsp;&amp;nbsp;,Categories&amp;nbsp;&amp;nbsp;&amp;nbsp;,Properties&amp;nbsp;&amp;nbsp;&amp;nbsp;,Docs&amp;nbsp;&amp;nbsp;&amp;nbsp;,Links&amp;nbsp;&amp;nbsp;&amp;nbsp;,Html&amp;nbsp;&amp;nbsp;&amp;nbsp;,SEO&amp;nbsp;&amp;nbsp;&amp;nbsp;,Extra.
        /// </summary>
        internal static string productdatasection_Text {
            get {
                return ResourceManager.GetString("productdatasection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Limit.
        /// </summary>
        internal static string productdocumentlimit_Text {
            get {
                return ResourceManager.GetString("productdocumentlimit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Limit.
        /// </summary>
        internal static string productimagelimit_Text {
            get {
                return ResourceManager.GetString("productimagelimit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Product Limit will not allow additional products to be added.  .
        /// </summary>
        internal static string productlimit_Msg {
            get {
                return ResourceManager.GetString("productlimit.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Limit.
        /// </summary>
        internal static string productlimit_Text {
            get {
                return ResourceManager.GetString("productlimit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Product Link Limit will not allow additional links to be added.  .
        /// </summary>
        internal static string productlinklimit_Msg {
            get {
                return ResourceManager.GetString("productlinklimit.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Link Limit.
        /// </summary>
        internal static string productlinklimit_Text {
            get {
                return ResourceManager.GetString("productlinklimit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Product Model Limit will not allow additional models to be added.  .
        /// </summary>
        internal static string productmodellimit_Msg {
            get {
                return ResourceManager.GetString("productmodellimit.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Model Limit.
        /// </summary>
        internal static string productmodellimit_Text {
            get {
                return ResourceManager.GetString("productmodellimit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string productname_Text {
            get {
                return ResourceManager.GetString("productname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Product Option Limit will not allow additional options to be added.  .
        /// </summary>
        internal static string productoptionlimit_Msg {
            get {
                return ResourceManager.GetString("productoptionlimit.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Option Limit.
        /// </summary>
        internal static string productoptionlimit_Text {
            get {
                return ResourceManager.GetString("productoptionlimit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &quot;Order By&quot; dropdown.
        /// </summary>
        internal static string productorderby_Text {
            get {
                return ResourceManager.GetString("productorderby.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string products_Text {
            get {
                return ResourceManager.GetString("products.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string properties_Text {
            get {
                return ResourceManager.GetString("properties.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string propertiesadmin_Text {
            get {
                return ResourceManager.GetString("propertiesadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string property_Text {
            get {
                return ResourceManager.GetString("property.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Groups.
        /// </summary>
        internal static string propertygroups_Text {
            get {
                return ResourceManager.GetString("propertygroups.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string protocol_Text {
            get {
                return ResourceManager.GetString("protocol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        internal static string providers_Text {
            get {
                return ResourceManager.GetString("providers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string qty_Text {
            get {
                return ResourceManager.GetString("qty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref..
        /// </summary>
        internal static string ref_Text {
            get {
                return ResourceManager.GetString("ref.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string region_Text {
            get {
                return ResourceManager.GetString("region.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Article.
        /// </summary>
        internal static string removearticle_confirm {
            get {
                return ResourceManager.GetString("removearticle.confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove History.
        /// </summary>
        internal static string removehistory_Text {
            get {
                return ResourceManager.GetString("removehistory.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting the store will restore all store settings to the default value for the system.  (Usually created by PortalShop Export).
        /// </summary>
        internal static string resetportalshop_Help {
            get {
                return ResourceManager.GetString("resetportalshop.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the store.
        /// </summary>
        internal static string resetportalshop_Text {
            get {
                return ResourceManager.GetString("resetportalshop.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Payment.
        /// </summary>
        internal static string retrypayment_Text {
            get {
                return ResourceManager.GetString("retrypayment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocket E-commerce.
        /// </summary>
        internal static string rocketecommerceapi_Text {
            get {
                return ResourceManager.GetString("rocketecommerceapi.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Domain.
        /// </summary>
        internal static string rootdomain_Text {
            get {
                return ResourceManager.GetString("rootdomain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        internal static string saleprice_Text {
            get {
                return ResourceManager.GetString("saleprice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string sales_Text {
            get {
                return ResourceManager.GetString("sales.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Send Email.
        /// </summary>
        internal static string saveandsend_Text {
            get {
                return ResourceManager.GetString("saveandsend.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Page URL.
        /// </summary>
        internal static string searchpageurl_Text {
            get {
                return ResourceManager.GetString("searchpageurl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Key.
        /// </summary>
        internal static string securitykey_Text {
            get {
                return ResourceManager.GetString("securitykey.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string sendemail_Text {
            get {
                return ResourceManager.GetString("sendemail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Email.
        /// </summary>
        internal static string sendreceivedemail_Text {
            get {
                return ResourceManager.GetString("sendreceivedemail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO.
        /// </summary>
        internal static string seo_Text {
            get {
                return ResourceManager.GetString("seo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting this store will define it as the default for all new portal stores created on this install. A &quot;default_portalshop.xml&quot; file is created in the RocketEcommerceAPI folder. When creating a new portal store, this XML data is used to create the new portal..
        /// </summary>
        internal static string setdefault_Help {
            get {
                return ResourceManager.GetString("setdefault.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default.
        /// </summary>
        internal static string setdefault_Text {
            get {
                return ResourceManager.GetString("setdefault.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string settingcountry_Text {
            get {
                return ResourceManager.GetString("settingcountry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_Text {
            get {
                return ResourceManager.GetString("settings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsadmin_Text {
            get {
                return ResourceManager.GetString("settingsadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetUp.
        /// </summary>
        internal static string setup_Text {
            get {
                return ResourceManager.GetString("setup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string shipping_Text {
            get {
                return ResourceManager.GetString("shipping.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string shippingaddress_Text {
            get {
                return ResourceManager.GetString("shippingaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Methods.
        /// </summary>
        internal static string shippingmethods_Text {
            get {
                return ResourceManager.GetString("shippingmethods.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Providers.
        /// </summary>
        internal static string shippingproviders_Text {
            get {
                return ResourceManager.GetString("shippingproviders.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want your order delivered?.
        /// </summary>
        internal static string shippingquestion_Text {
            get {
                return ResourceManager.GetString("shippingquestion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Email (SMTP).
        /// </summary>
        internal static string smtpfromemail_Text {
            get {
                return ResourceManager.GetString("smtpfromemail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        internal static string sortorder_Text {
            get {
                return ResourceManager.GetString("sortorder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instruction.
        /// </summary>
        internal static string specialinstructions_Text {
            get {
                return ResourceManager.GetString("specialinstructions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL filter is a section of SQL that interacts with the database SPROC to do a selection.  This is nearly always a text search, but it can be defined to whatever you wish.  The basic idea is to get the search text from the users then do a SPROC call with this filter.  The tokens in &quot;{&quot; &quot;}&quot; will be replaced with the SessionParam field name..
        /// </summary>
        internal static string sqlfilter_Help {
            get {
                return ResourceManager.GetString("sqlfilter.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Filter.
        /// </summary>
        internal static string sqlfilter_Text {
            get {
                return ResourceManager.GetString("sqlfilter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order SQL Filter .
        /// </summary>
        internal static string sqlfilterorder_Text {
            get {
                return ResourceManager.GetString("sqlfilterorder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment SQL Filter.
        /// </summary>
        internal static string sqlfilterpayment_Text {
            get {
                return ResourceManager.GetString("sqlfilterpayment.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product SQL Filter .
        /// </summary>
        internal static string sqlfilterproduct_Text {
            get {
                return ResourceManager.GetString("sqlfilterproduct.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of SQL order by clauses, this will be used in the &quot;order by&quot; dropdownlist to give different sort order to the product list. On large databases a index may be required on the table to ensure performace&lt;/i&gt;.
        /// </summary>
        internal static string sqlorderby_Help {
            get {
                return ResourceManager.GetString("sqlorderby.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp;uarr;.
        /// </summary>
        internal static string sqlorderby_product_name_desc_Text {
            get {
                return ResourceManager.GetString("sqlorderby-product-name-desc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp;darr;.
        /// </summary>
        internal static string sqlorderby_product_name_Text {
            get {
                return ResourceManager.GetString("sqlorderby-product-name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price &amp;uarr;.
        /// </summary>
        internal static string sqlorderby_product_price_desc_Text {
            get {
                return ResourceManager.GetString("sqlorderby-product-price-desc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price &amp;darr;.
        /// </summary>
        internal static string sqlorderby_product_price_Text {
            get {
                return ResourceManager.GetString("sqlorderby-product-price.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. &amp;uarr;.
        /// </summary>
        internal static string sqlorderby_product_ref_desc_Text {
            get {
                return ResourceManager.GetString("sqlorderby-product-ref-desc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. &amp;darr;.
        /// </summary>
        internal static string sqlorderby_product_ref_Text {
            get {
                return ResourceManager.GetString("sqlorderby-product-ref.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Order By.
        /// </summary>
        internal static string sqlorderby_Text {
            get {
                return ResourceManager.GetString("sqlorderby.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL OrderBy Order.
        /// </summary>
        internal static string sqlorderbyorder_Text {
            get {
                return ResourceManager.GetString("sqlorderbyorder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL OrderBy Article.
        /// </summary>
        internal static string sqlorderbyproduct_Text {
            get {
                return ResourceManager.GetString("sqlorderbyproduct.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static List.
        /// </summary>
        internal static string staticlist_Text {
            get {
                return ResourceManager.GetString("staticlist.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status_Text {
            get {
                return ResourceManager.GetString("status.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string storename_Text {
            get {
                return ResourceManager.GetString("storename.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string street_Text {
            get {
                return ResourceManager.GetString("street.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        internal static string subtotal_Text {
            get {
                return ResourceManager.GetString("subtotal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string summary_Text {
            get {
                return ResourceManager.GetString("summary.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string support_Text {
            get {
                return ResourceManager.GetString("support.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string tax_Text {
            get {
                return ResourceManager.GetString("tax.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Methods.
        /// </summary>
        internal static string taxmethods_Text {
            get {
                return ResourceManager.GetString("taxmethods.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        internal static string taxnumber_Text {
            get {
                return ResourceManager.GetString("taxnumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Providers.
        /// </summary>
        internal static string taxproviders_Text {
            get {
                return ResourceManager.GetString("taxproviders.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel..
        /// </summary>
        internal static string tel_Text {
            get {
                return ResourceManager.GetString("tel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tools_Text {
            get {
                return ResourceManager.GetString("tools.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total_Text {
            get {
                return ResourceManager.GetString("total.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        internal static string uilanguage_Text {
            get {
                return ResourceManager.GetString("uilanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string unit_Text {
            get {
                return ResourceManager.GetString("unit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string url_Text {
            get {
                return ResourceManager.GetString("url.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Billing Address for Shiping..
        /// </summary>
        internal static string usebillingaddress_Text {
            get {
                return ResourceManager.GetString("usebillingaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        internal static string usersettings_Text {
            get {
                return ResourceManager.GetString("usersettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of valid remote portal keys.  If  the website API is called by a remote website.  The remote module must pass a portal key.  This key should match 1 of the values in this list, otherwise the call will be rejected.  (A minimum length of 8 characters is required) **.
        /// </summary>
        internal static string validportalkeys_Help {
            get {
                return ResourceManager.GetString("validportalkeys.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote portal key.
        /// </summary>
        internal static string validportalkeys_Text {
            get {
                return ResourceManager.GetString("validportalkeys.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value_Text {
            get {
                return ResourceManager.GetString("value.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display AppTheme.
        /// </summary>
        internal static string viewapptheme_Text {
            get {
                return ResourceManager.GetString("viewapptheme.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        internal static string viewcart_Text {
            get {
                return ResourceManager.GetString("viewcart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        internal static string websiteurl_Text {
            get {
                return ResourceManager.GetString("websiteurl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string weight_Text {
            get {
                return ResourceManager.GetString("weight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Contact Details.
        /// </summary>
        internal static string yourcontactdetails_Text {
            get {
                return ResourceManager.GetString("yourcontactdetails.Text", resourceCulture);
            }
        }
    }
}
