//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocketEcommerceAPI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SideMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SideMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocketEcommerceAPI.App_LocalResources.SideMenu", typeof(SideMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string catalog_Text {
            get {
                return ResourceManager.GetString("catalog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string categoryadmin_Text {
            get {
                return ResourceManager.GetString("categoryadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string company_Text {
            get {
                return ResourceManager.GetString("company.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard_Text {
            get {
                return ResourceManager.GetString("dashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Methods.
        /// </summary>
        internal static string discountmethods_Text {
            get {
                return ResourceManager.GetString("discountmethods.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string notification_Text {
            get {
                return ResourceManager.GetString("notification.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Admin.
        /// </summary>
        internal static string orderadmin_Text {
            get {
                return ResourceManager.GetString("orderadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        internal static string paymentadmin_Text {
            get {
                return ResourceManager.GetString("paymentadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        internal static string paymentmethods_Text {
            get {
                return ResourceManager.GetString("paymentmethods.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string productadmin_Text {
            get {
                return ResourceManager.GetString("productadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string propertiesadmin_Text {
            get {
                return ResourceManager.GetString("propertiesadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string propertyadmin_Text {
            get {
                return ResourceManager.GetString("propertyadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string rocketecommerceadmin_Text {
            get {
                return ResourceManager.GetString("rocketecommerceadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string sales_Text {
            get {
                return ResourceManager.GetString("sales.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string settingcountry_Text {
            get {
                return ResourceManager.GetString("settingcountry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_Text {
            get {
                return ResourceManager.GetString("settings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsadmin_Text {
            get {
                return ResourceManager.GetString("settingsadmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Methods.
        /// </summary>
        internal static string shippingmethods_Text {
            get {
                return ResourceManager.GetString("shippingmethods.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Methods.
        /// </summary>
        internal static string taxmethods_Text {
            get {
                return ResourceManager.GetString("taxmethods.Text", resourceCulture);
            }
        }
    }
}
